"""
Main generation endpoints.
"""
from datetime import datetime
from typing import Dict, Any

from fastapi import APIRouter, HTTPException, WebSocket, WebSocketDisconnect

from app.models import (
    GenerationInputs, GenerationConfiguration, GenerationRequest, GenerationResponse
)
from app.services.generation_service import GenerationService

router = APIRouter(prefix="/api/generate", tags=["generation"])

# WebSocket connection manager
class ConnectionManager:
    def __init__(self):
        self.active_connections: Dict[str, WebSocket] = {}
    
    async def connect(self, request_id: str, websocket: WebSocket):
        await websocket.accept()
        self.active_connections[request_id] = websocket
    
    def disconnect(self, request_id: str):
        if request_id in self.active_connections:
            del self.active_connections[request_id]
    
    async def send_message(self, request_id: str, message: Dict[str, Any]):
        if request_id in self.active_connections:
            await self.active_connections[request_id].send_json(message)

manager = ConnectionManager()


@router.post("")
async def generate(request: Dict[str, Any]) -> GenerationResponse:
    """
    Generate test plan and test cases.
    
    Request body:
    {
        "inputs": {
            "jira_id": "PROJ-123",
            "valueedge_id": null,
            "files": [...],
            "custom_prompt": "..."
        },
        "configuration": {
            "provider": "groq",
            "model": "llama-3.3-70b-versatile",
            "temperature": 0.2
        }
    }
    """
    try:
        inputs = GenerationInputs(**request.get("inputs", {}))
        config = GenerationConfiguration(**request.get("configuration", {}))
        
        service = GenerationService()
        
        # Validate at least one input source
        if not inputs.jira_id and not inputs.valueedge_id and not inputs.files:
            raise HTTPException(400, "At least one input source required (JIRA, ValueEdge, or files)")
        
        gen_request = GenerationRequest(
            request_id="",  # Will be generated by service
            timestamp=datetime.utcnow(),
            inputs=inputs,
            configuration=config
        )
        
        return await service.generate(inputs, config)
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(500, f"Generation failed: {str(e)}")


@router.websocket("/ws/{request_id}")
async def websocket_generate(websocket: WebSocket, request_id: str):
    """WebSocket endpoint for streaming generation."""
    await manager.connect(request_id, websocket)
    
    try:
        # Receive generation request
        data = await websocket.receive_json()
        
        inputs = GenerationInputs(**data.get("inputs", {}))
        config = GenerationConfiguration(**data.get("configuration", {}))
        
        # Validate inputs
        if not inputs.jira_id and not inputs.valueedge_id and not inputs.files:
            await manager.send_message(request_id, {
                "type": "error",
                "error": "At least one input source required"
            })
            return
        
        service = GenerationService()
        
        async def progress_callback(update: Dict[str, Any]):
            await manager.send_message(request_id, {
                "type": "progress",
                **update
            })
        
        result = await service.generate(inputs, config, progress_callback)
        
        await manager.send_message(request_id, {
            "type": "completed",
            "result": result.model_dump()
        })
        
    except WebSocketDisconnect:
        pass
    except Exception as e:
        await manager.send_message(request_id, {
            "type": "error",
            "error": str(e)
        })
    finally:
        manager.disconnect(request_id)


@router.get("/{request_id}")
async def get_generation_status(request_id: str) -> Dict[str, Any]:
    """Get generation status/result by ID."""
    # This would fetch from database in a real implementation
    return {"status": "not_implemented", "request_id": request_id}
