"""
Main generation endpoints.
"""
import uuid
from datetime import datetime
from typing import Dict, Any

from fastapi import APIRouter, HTTPException, WebSocket, WebSocketDisconnect

from app.models import (
    GenerationInputs, GenerationConfiguration, GenerationRequest, GenerationResponse,
    GenerationOutputs, GenerationMetadata
)
from app.services.generation_service import GenerationService

router = APIRouter(prefix="/api/generate", tags=["generation"])

# WebSocket connection manager
class ConnectionManager:
    def __init__(self):
        self.active_connections: Dict[str, WebSocket] = {}
    
    async def connect(self, request_id: str, websocket: WebSocket):
        await websocket.accept()
        self.active_connections[request_id] = websocket
    
    def disconnect(self, request_id: str):
        if request_id in self.active_connections:
            del self.active_connections[request_id]
    
    async def send_message(self, request_id: str, message: Dict[str, Any]):
        if request_id in self.active_connections:
            await self.active_connections[request_id].send_json(message)

manager = ConnectionManager()


def _has_custom_instructions(inputs: GenerationInputs) -> bool:
    return any([
        bool(inputs.custom_prompt and inputs.custom_prompt.strip()),
        bool(inputs.test_plan_prompt and inputs.test_plan_prompt.strip()),
        bool(inputs.test_case_prompt and inputs.test_case_prompt.strip()),
    ])


def _has_any_input(inputs: GenerationInputs) -> bool:
    return bool(
        inputs.jira_id
        or getattr(inputs, "jira_ids", None)
        or inputs.valueedge_id
        or getattr(inputs, "valueedge_ids", None)
        or inputs.files
        or _has_custom_instructions(inputs)
    )


def _friendly_error_message(error: str, provider: str, model: str) -> str:
    if not error:
        return error
    lower = error.lower()
    if provider == "groq" and ("rate limit" in lower or "rate_limit_exceeded" in lower or "error code: 429" in lower):
        return (
            f"Groq token/day limit reached for model '{model}'. "
            "Please switch to another Groq model, use Ollama local provider, or retry after quota reset."
        )
    return error


@router.post("")
async def generate(request: Dict[str, Any]) -> GenerationResponse:
    """
    Generate test plan and test cases.
    
    Request body:
    {
        "inputs": {
            "jira_id": "PROJ-123",
            "valueedge_id": null,
            "files": [...],
            "custom_prompt": "..."
        },
        "configuration": {
            "provider": "groq",
            "model": "llama-3.3-70b-versatile",
            "temperature": 0.2
        }
    }
    """
    try:
        inputs = GenerationInputs(**request.get("inputs", {}))
        config = GenerationConfiguration(**request.get("configuration", {}))
        
        service = GenerationService()
        
        # Validate at least one input source
        if not _has_any_input(inputs):
            raise HTTPException(400, "At least one input source required (ticket, document, or custom instructions)")
        
        gen_request = GenerationRequest(
            request_id="",  # Will be generated by service
            timestamp=datetime.utcnow(),
            inputs=inputs,
            configuration=config
        )
        
        result = await service.generate(inputs, config)
        if result.status == "failed" and result.error:
            result.error = _friendly_error_message(result.error, config.provider, config.model or "unknown")
        return result

    except HTTPException as e:
        return GenerationResponse(
            request_id=str(uuid.uuid4()),
            status="failed",
            timestamp=datetime.utcnow(),
            outputs=GenerationOutputs(),
            metadata=GenerationMetadata(
                model_used=request.get("configuration", {}).get("model", "unknown"),
                temperature=request.get("configuration", {}).get("temperature", 0.2),
                sources=[]
            ),
            error=str(e.detail)
        )
    except Exception as e:
        return GenerationResponse(
            request_id=str(uuid.uuid4()),
            status="failed",
            timestamp=datetime.utcnow(),
            outputs=GenerationOutputs(),
            metadata=GenerationMetadata(
                model_used=request.get("configuration", {}).get("model", "unknown"),
                temperature=request.get("configuration", {}).get("temperature", 0.2),
                sources=[]
            ),
            error=f"Generation failed: {str(e)}"
        )


@router.websocket("/ws/{request_id}")
async def websocket_generate(websocket: WebSocket, request_id: str):
    """WebSocket endpoint for streaming generation."""
    await manager.connect(request_id, websocket)
    
    try:
        # Receive generation request
        data = await websocket.receive_json()
        
        inputs = GenerationInputs(**data.get("inputs", {}))
        config = GenerationConfiguration(**data.get("configuration", {}))
        
        # Validate inputs
        if not _has_any_input(inputs):
            await manager.send_message(request_id, {
                "type": "error",
                "error": "At least one input source required (ticket, document, or custom instructions)"
            })
            return
        
        service = GenerationService()
        
        async def progress_callback(update: Dict[str, Any]):
            await manager.send_message(request_id, {
                "type": "progress",
                **update
            })
        
        result = await service.generate(inputs, config, progress_callback)
        
        await manager.send_message(request_id, {
            "type": "completed",
            "result": result.model_dump()
        })
        
    except WebSocketDisconnect:
        pass
    except Exception as e:
        await manager.send_message(request_id, {
            "type": "error",
            "error": str(e)
        })
    finally:
        manager.disconnect(request_id)


@router.get("/{request_id}")
async def get_generation_status(request_id: str) -> Dict[str, Any]:
    """Get generation status/result by ID."""
    # This would fetch from database in a real implementation
    return {"status": "not_implemented", "request_id": request_id}
